# Generated by Django 5.1.3 on 2024-11-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arcade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='ap_materno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ap_paterno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
