# Generated by Django 5.1.3 on 2024-11-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arcade', '0006_videojuego'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='marca',
        ),
        migrations.AddField(
            model_name='videojuego',
            name='consola',
            field=models.TextField(null=True, verbose_name='id_consola'),
        ),
        migrations.AddField(
            model_name='videojuego',
            name='genero',
            field=models.CharField(max_length=100, null=True, verbose_name='Genero'),
        ),
    ]
